# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 00:51
from __future__ import unicode_literals

import UI.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to=UI.models.user_directory_path)),
                ('applicant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('no_of_vacancies', models.IntegerField()),
                ('degree', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('work_exp', models.CharField(max_length=100)),
            ],
        ),
    ]
