# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 01:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appliers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 1, 29, 1, 457381)),
        ),
    ]
