# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20170621_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 13, 26, 48, 225886)),
        ),
    ]
