# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 10:26
from __future__ import unicode_literals

import UI.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UI', '0003_auto_20170621_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to=UI.models.user_directory_path)),
                ('extractedSkill', models.TextField()),
                ('extractedWorkExp', models.TextField()),
                ('extractedCert', models.TextField()),
                ('extractedEdu', models.TextField()),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='applicant',
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 10, 26, 27, 633023)),
        ),
        migrations.DeleteModel(
            name='Cv',
        ),
    ]
