# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_auto_20170727_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='appliers',
            field=models.ManyToManyField(blank=True, null=True, to='UI.Applicant'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 11, 31, 23, 847041)),
        ),
    ]
