# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0007_auto_20170729_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='extractedCert',
            new_name='applicant_Cert',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='extractedEdu',
            new_name='applicant_Edu',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='extractedSkill',
            new_name='applicant_Skill',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='extractedWorkExp',
            new_name='applicant_WorkExp',
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 8, 5, 14, 51, 6, 917180)),
        ),
    ]
