# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0008_auto_20170729_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='no_of_vacancies',
            new_name='number_of_vacancies',
        ),
        migrations.RemoveField(
            model_name='job',
            name='work_exp',
        ),
        migrations.AddField(
            model_name='job',
            name='certification',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 8, 5, 15, 36, 53, 954867)),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.TextField(),
        ),
    ]
