# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0009_auto_20170729_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='certification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 8, 5, 15, 52, 15, 418140)),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
