# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0010_auto_20170729_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_Cert',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_Edu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_Skill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_WorkExp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 8, 5, 18, 51, 6, 631423)),
        ),
    ]
