# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0011_auto_20170729_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skill_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='work_experience_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 6, 8, 23, 536085)),
        ),
    ]
