# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0015_auto_20170730_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='skill_link',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='work_experience_link',
        ),
        migrations.AddField(
            model_name='applicant',
            name='skill_ontology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='woek_experience_ontology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2017, 8, 7, 7, 40, 5, 459091)),
        ),
    ]
