# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0017_auto_20170731_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='woek_experience_ontology',
            new_name='work_experience_ontology',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(default='static/user_photos/silhouette.png', upload_to='static/user_photos'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 14, 7, 58, 867490, tzinfo=utc)),
        ),
    ]
