# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0021_auto_20170805_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='appliedAt',
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='appliedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 12, 6, 18, 47, 650197, tzinfo=utc)),
        ),
    ]
